# Generated by Django 5.2.14 on 2026-05-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='edited_by_analyst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
